.annotations_sample, code_annotations/cli.py, code_annotations/exceptions.py, code_annotations/extensions/__init__.py, code_annotations/extensions/base.py, code_annotations/extensions/javascript.py, code_annotations/extensions/plaintext.py, code_annotations/find_annotations.py, code_annotations/helpers.py, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/test.txt, setup.cfg, setup.py, tests/test_code_annotations.py, tox.ini
**Description:** A skeleton implementation of static annotation configuration, search, reporting, and extensions.
**JIRA:** PLAT-2350, PLAT-2361, PLAT-2365
**Installation instructions:** To test with the extensions you will need to install the package with `pip install --editable .`
0. Make sure the package is installed as above
1. Add some annotations to various files
2. Use the `.annotations_sample` as a template to create your own config file, or just point to it on the command line if you're using the `.. pii::` annotations
3. Run `find_annotations`. If things are misbehaving try the various levels of verbosity (`-v` - `-vvv`)
finished.
**Author concerns:** 
- There are a lot of TODO items, mostly things to be addressed in …
=> Stub implementation of static annotation search and plaintext extension

code_annotations/cli.py, code_annotations/find_annotations.py, code_annotations/helpers.py, tests/extensions/test_extension_javascript.py, tests/extensions/test_extension_python.py, tests/test_find_annotations.py
**Description:** Adds new options `lint/no-lint` and `report/no-report` to allow the linting and reporting functionality to be run separately. Both default to being on. Since the linting actually occurs at the script level no language extension changes were needed.
**JIRA:** PLAT-2349, PLAT-2353
=> Allow static linting and reporting to be turned on and off separately

code_annotations/__init__.py, code_annotations/base.py, code_annotations/find_django.py, code_annotations/helpers.py, tests/test_find_django.py
Also adds a comment to the top of the safelist to clarify that
annotations need to be added and highlights that fact in the seed
safelist command.
=> Fix coverage count of safelisted Django models

docs/configuration.rst, docs/django_search.rst, docs/extensions.rst, docs/getting_started.rst, docs/index.rst, docs/static_search.rst, docs/writing_annotations.rst
**Description:** Adds documentation for the search tools, cleans up some things which have grown inaccurate.
**JIRA:** PLAT-2402
=> Update and fill out documentation

code_annotations/__init__.py, code_annotations/find_django.py
The first model would appear in the default comment, fix is to only `lstrip` the comment, leaving the intended whitespace.
=> Fix a bug with default safelist generation

code_annotations/base.py, code_annotations/cli.py, tests/test_base.py, tests/test_configurations/.annotations_test_duplicate_token, tests/test_configurations/.annotations_test_duplicate_token_2_groups, tests/test_configurations/.annotations_test_group_one_token, tests/test_find_django.py
**Description:** Perform basic checks to make sure configured annotations will work correctly, and make the `coverage_target` configuration variable optional (but checked before use).
=> Improve annotation configuration checks, make coverage_target optional

Makefile, docs/getting_started.rst
**Description:** Re-enables the ability to run pytest / "make test" out of the box.
1. Create a new virtualenv and source it
2. In the Code Annotations top level directory run a `make requirements`
3. Run `make test` all tests should succeed
4. Run `pytest` all tests should succeed
5. Confirm that the "Getting Started" doc roughly adequately describes how to install the app and run tests.
=> Fix setup instructions, test requirements

docs/getting_started.rst
**Description:** Just a quick formatting update to the Getting Started doc
=> Fixup formatting issue with the Getting Started doc

code_annotations/__init__.py, code_annotations/base.py, code_annotations/cli.py
Bump version.
**Description:** Add prefixing of report filename. Change elapsed time to seconds. 
**JIRA:** Link to JIRA ticket
**Dependencies:** dependencies on other outstanding PRs, issues, etc. 
**Merge deadline:** List merge deadline (if any)
**Installation instructions:** List any non-trivial installation 
instructions.
1. Do thing A
2. Expect B to happen
3. If C happened instead - check failed.
**Reviewers:**
finished.
**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.
=> Add prefixing of report filename. Change elapsed time to seconds. 

.travis.yml, Makefile, code_annotations/__init__.py, code_annotations/base.py, code_annotations/cli.py, code_annotations/exceptions.py, code_annotations/find_django.py, code_annotations/generate_docs.py, code_annotations/helpers.py, pylintrc, pylintrc_tweaks, requirements/base.in, requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.in, requirements/test.txt, requirements/travis.txt, setup.py, tests/helpers.py, tox.ini
**Description:** This PR updates code-annotations to be compatibile with django 2.2.  It also adds tox environments for testing django 1.11, 2.0, 2.1, 2.2.  Finally it fixes some lint errors that arose while updating dependencies.
**JIRA:** Link to JIRA ticket
**Dependencies:** dependencies on other outstanding PRs, issues, etc. 
**Merge deadline:** List merge deadline (if any)
**Installation instructions:** List any non-trivial installation 
instructions.
1. Do thing A
2. Expect B to happen
3. If C happened instead - check failed.
**Reviewers:**
finished.
**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.
=> PROD-1074: Upgrade to django 2.2.

CHANGELOG.rst, README.rst, config_and_tools/README.rst, docs/decisions/0001-config-and-tools.rst, tox.ini
**Description:**
ADR for adding a home for shared annotation configs and
supporting tools in this repository.
See docs/decisions/0001-config-and-tools.rst
For more discussion leading up to this decision, see https://github.com/edx/edx-platform/pull/24344#issuecomment-664532414
**JIRA:**
ARCHBOM-1387
=> ARCHBOM-1387: ADR for config-and-tools

CHANGELOG.rst, code_annotations/__init__.py, code_annotations/config_and_tools/sphinx/extensions/featuretoggles.py
**Description:** Add support for `toggle_warning` flags in the `featuretoggles` Sphinx extension
**JIRA:** https://openedx.atlassian.net/wiki/spaces/COMM/pages/1596358943
**Dependencies:** None. But useful for documenting edx-platform feature toggles.
**Reviewers:**
- ~~[ ] Documentation updated (not only docstrings)~~
finished.
=> [BD-21] Add support for warnings in the `featuretoggles` Sphinx extension

CHANGELOG.rst, code_annotations/__init__.py, code_annotations/extensions/base.py, tests/extensions/python_test_files/multiline_singlelinecomment.pyt, tests/extensions/test_base_extensions.py, tests/extensions/test_extension_python.py
**Description:**
Multiline annotations were previously supported only for multi-line comments. In Python: """..."""
This introduces multiline annotations for comments prefixed by single-line comment signs. In Python:
This makes it possible to wrap long comment lines more naturally, in particular in Python.
**JIRA:** https://openedx.atlassian.net/wiki/spaces/COMM/pages/1596358943
**Dependencies:** This feature can be tested on this PR: https://github.com/edx/edx-platform/pull/24815
**Reviewers:**
finished.
=> [BD-21] Multiline annotations with single-line comment prefix ("#")

CHANGELOG.rst, code_annotations/__init__.py, code_annotations/contrib/config/feature_toggle_annotations.yaml
**Description:** This is nowhere used. If we need to re-introduce it at some point, we'll
discuss it then.
**JIRA:** BD-21 https://openedx.atlassian.net/wiki/spaces/COMM/pages/1596358943
**Reviewers:**
finished.
**Author concerns:** List any concerns about this PR - inelegant
solutions, hacks, quick-and-dirty implementations, concerns about
migrations, etc.
=> [BD-21] Get rid of the `documented_elsewhere` annotation

CHANGELOG.rst, code_annotations/__init__.py, code_annotations/base.py
Annotation grouping was based on the filename and line number. Unfortunately,
this fails when the annotation comes from the safelist, where the filename is
the safelist, and the line number is 0. This was causing issues in pii
annotation parsing on edx-platform. To address this, we group annotations by
line number and extra[model_id] fields.
**Description:** Describe in a couple of sentence what this PR adds
**JIRA:** Link to JIRA ticket
**Dependencies:** dependencies on other outstanding PRs, issues, etc.
**Merge deadline:** List merge deadline (if any)
**Installation instructions:** List any non-trivial installation
instructions.
The following command was triggering errors for all safelisted annotations:
```
DJANGO_SETTINGS_MODULE=lms.envs.test code_annotations …
```
=> [BD-21] Fix grouping of safelisted annotations

CHANGELOG.rst, code_annotations/__init__.py, code_annotations/contrib/config/setting_annotations.yaml
**Description:**
make setting_warning annotation optional
finished.
=> make setting_warning annotation optional

CHANGELOG.rst, code_annotations/__init__.py, requirements/base.in
- Remove click constraint from `base.in` file.
- Bump the version to `1.1.2`.
- Requirements upgrade jobs in several packages are failing due to the base constraint of `click<8.0` required in the code-annotations package. 
- code-annotations has constraint `click<8.0` in `base.in` file which is being used in `edx-lint` latest version and `edx-lint` is in-turn being used in code-annotations. This makes it a circular dependency so we can't run make upgrade along with removing the constraint. 
- After merging this PR, the code-annotations version will be changed in `edx-lint` which will remove the effect of circular dependencies and hence will allow us to update the requirements. 
- The change is verified to resolve the upgrade issue by using the hash commit of this PR in the edx-lint sample …
=> Remove click constraint

Makefile, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/django.txt, requirements/doc.in, requirements/doc.txt, requirements/pip-tools.txt, requirements/pip.txt, requirements/quality.txt, requirements/test.txt, setup.py, tox.ini
Updated the upgrade target script to check the compatibility of upgraded pip and pip-tools versions.
For reference, look at this https://github.com/openedx/edx-repo-health/pull/271 for new check added in edx-repo-health.
JIRA:https://2u-internal.atlassian.net/browse/BOM-3456
=> fix: Install pip and pip-tools in upgrade script

code_annotations/contrib/sphinx/extensions/featuretoggles.py, code_annotations/contrib/sphinx/extensions/settings.py
- This commit make it possible to render extra toggle fields
if they are defiend.
- It also ids fields for the nodes, in order to be easily
extact these fields.
Please look at photo below to see the different, notice the new extra fields added.
=> fix: redner optional toggle fields when exists

CHANGELOG.rst, code_annotations/__init__.py, code_annotations/base.py, code_annotations/cli.py, code_annotations/generate_docs.py
- Use `utcnow()` instead of `now()` for elapsed time, because the `now()` clock can easily change. I was getting "Search found 8 annotations in -17999.895582 seconds." from some runs of pii_check, and I narrowed it down to `DjangoSearch(config)` changing the clock. Presumably something is hardcoding Eastern Standard Time somewhere. (It's EDT right now!) There might be a better timer utility somewhere, but this should at least be correct when leap seconds and NTP updates aren't involved. :-)
- Make the timestamp in the report filename go year-month-day rather than year-day-month. Also make it more compact while I'm in there.
=> fix: Fix timestamp handling (elapsed; formatting)

code_annotations/contrib/config/openedx_events_annotations.yaml, code_annotations/contrib/sphinx/extensions/openedx_events.py
Add warning for openedx-events annotations so developers can include relevant information about the current event. As for now, these warnings have been used to indicate that the event at the time of implementation doesn't have for the event bus.
1. Create a venv 
2. Install this version of openedx-events which uses `.. event_warning` instead of a `Warning: ` label.
3. Generate docs for openedx-events by running: `make docs`
Here's the expected output:
=> feat: add support for optional event warning for in-line annotation

code_annotations/contrib/config/__init__.py
**Description:** Resolves #114 
**JIRA:** nil
**Dependencies:** nil
**Merge deadline:** nil
**Installation instructions:** nil
**Testing instructions:** nil
**Reviewers:**
finished.
**Author concerns:** nil
=> #114: Migrate to importlib

requirements/ci.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip.txt
**Description:** We're no longer supporting Python 3.9 and tox 4 has been around for a long time now, it's in use in edx-platform so should be safe here.
=> chore: Loosen requirement constraints

CHANGELOG.rst, code_annotations/__init__.py, code_annotations/contrib/config/__init__.py, code_annotations/contrib/config/openedx_events_annotations.yaml, code_annotations/contrib/sphinx/extensions/openedx_events.py
Add triggering fields for opened-events annotations so developers can include relevant information about where the event is being triggered by rendering a link that redirects to a GH search with the source file and the event name. 
1. Create a venv 
2. Install [this](https://github.com/openedx/openedx-events/pull/443) version of openedx-events which uses `event_trigger_repository` and `event_trigger_path`
3. Generate docs for openedx-events by running: `make docs`
You can also review the rendered docs here: https://docsopenedxorg--443.org.readthedocs.build/projects/openedx-events/en/443/
**Merge Checklist:**
**Post Merge:**
finished.
=> feat: [FC-0074] add support for optional trigger information

docs/conf.py, docs/contrib/how_to/add_new_annotations_and_extracted_docs.rst, docs/contrib/how_to/documenting_django_settings.rst
We've moved a lot of documentation to docs.openedx.org, so update the edx.rtd.io links in this repo.
=> docs: update edx.rtd links to docs.openedx.org
